//XFZKGJMIXEBENNALHJGHAZGKEZSWTPPVIELEQERQNWEPPVEFQPFIOABBACVEWDEOPXCNUOCDATHKBSMNEEOLDJMYDYXRKQJDEOBV
//SLBONSFBFDOWDZZCFQSMCXXIYZVAHRGMREIITGDNNLJRZEPIOLCZCASSKWQHCSGAJABOZBNLIPYWORSAAEUNAPUHLFVOAXEPRCYA
//
//  YJHYUkCenterHistoryListViewController.h
//  AFNetworking
//
//  Created by oceanMAC on 2023/5/5.
//

#import <HYBaseTool/HYBaseTool.h>
#import "YJHYUkVideoBaseViewController.h"

NS_ASSUME_NONNULL_BEGIN

@interface YJHYUkCenterHistoryListViewController : YJHYUkVideoBaseViewController

@end

NS_ASSUME_NONNULL_END
