//GVRRHBAJECJMJKBEYXPYCQNGYDACNMKKFTHFWRUQSXCIGQOLWSEQHWYDWZPHGUHEGTWXEVLQMSDKSLCAPHHPKTYOONLTCWLCZIIP
//
//  YJHYUKHistoryRecodeView.h
//  HYUKSDK
//
//  Created by oceanMAC on 2023/6/8.
//

#import <UIKit/UIKit.h>
#import <HYBaseTool/HYBaseTool.h>
#import "HYUkHeader.h"

NS_ASSUME_NONNULL_BEGIN

@interface YJHYUKHistoryRecodeView : HYBaseView

@end

NS_ASSUME_NONNULL_END
