//GMGSFBOFPZDJAQHATTXBAVRHJNOSDPFKGLVYFZHEHGAFWYJEWLFKMPMDYOLCFKBOZBJFSYBEGGQXABINQAZYWNRKIEMLNYHQUVOW
//LVPDNUVOIYDEAWYEYQOMQSFTXZUZAZPVVIMESHRBNSFXUXKRZPLXQJJMEYRKYFQOGULJKQUZLIRVQNEIJSGGNVFUAJWTADVDUMOF
//
//  YJHYUkSearchViewController.h
//  AFNetworking
//
//  Created by oceanMAC on 2023/4/27.
//

#import <UIKit/UIKit.h>
#import <HYBaseTool/HYBaseTool.h>
#import "YJHYUkVideoBaseViewController.h"

NS_ASSUME_NONNULL_BEGIN

@interface YJHYUkSearchViewController : YJHYUkVideoBaseViewController

@end

NS_ASSUME_NONNULL_END
