//AMBDTEOTNWOYBXXNCNXQTHFSMEOGXXFOAGIBIJUMHTRYMVHLDXQKRMZNMOBHZYLWCKOEDMBYQHOGRGXXJUDEQRHFOTZDJECIJHKS
//NIDWSGDCHQWJZEBBPIAIGVIRZDGQSFMHDOSFJCMBIPNROIMGEXEPUIWILUOXVLFYWFQCSKXPVRVQBITHIBUYCBXHERLMIWPILIUW
//
//  YJHYUKRecommendViewController.h
//  HYUKSDK
//
//  Created by oceanMAC on 2023/10/11.
//

#import "YJHYUkBaseListViewController.h"

NS_ASSUME_NONNULL_BEGIN

@interface YJHYUKRecommendViewController : YJHYUkBaseListViewController

@end

NS_ASSUME_NONNULL_END
