//EEAJEWTHLMKVSQMORAZIPNGGTALAUBHVXKISQSDGUQOLWYRGXEWZEWZZGPIWPFSQOQJZLNILUAALJVBDIKACJLLCZCABDKDKODXF
//
//  YJHYUkHistoryView.h
//  HYUKSDK
//
//  Created by oceanMAC on 2023/4/28.
//

#import <HYBaseTool/HYBaseTool.h>
#import "HYUkHeader.h"

NS_ASSUME_NONNULL_BEGIN

@interface YJHYUkHistoryView : HYBaseView

@end

NS_ASSUME_NONNULL_END
