use_frameworks!

platform :ios, '10.0'

target 'HYVideoPlay_Example' do
  pod 'HYVideoPlay', :path => '../'

  
  post_install do |pi|
    
    xcode_base_version = `xcodebuild -version | grep 'Xcode' | awk '{print $2}' | cut -d . -f 1`
    pi.pods_project.targets.each do |t|
      t.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '13.0'
          xcconfig_path = config.base_configuration_reference.real_path
          xcconfig = File.read(xcconfig_path)
          xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
          File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
        
      end
    end
  end
  
  target 'HYVideoPlay_Tests' do
    inherit! :search_paths

    
  end
end
